### ISSUE TITLE
Poor performance with optional columns

### ISSUE THREAD

**Issue by BalassaMarton** [hughbe/excel-mapper#37]
Sadly, this is more of a design problem, and only a breaking change could fix it: when we make a column optional using `OptionalCellValueReader`, and the column is actually missing, importing _N_ lines with _K_ missing columns will throw and catch _N_*_K_ exceptions, dramatically degrading performance. 
#### Proposed solution ####
Instead of throwing an exception, `ReadCellValueResult` could have a `Success` property that tells if the cell was read. The exception should be thrown only at the end of the chain, before invoking the cell value mappers, if none of the readers have reported success.

**Comment by hughbe** [comment]
Happy to take the breaking change if you can show perf numbers and submit a PR :)

**Comment by BalassaMarton** [comment]
THB I decided to fork this project many times, but never had the time :) As soon as I have some capacity, I'll do that PR

**Comment by jeffolmstead** [comment]
First off, thanks for the great tooling, thanks so much! Just dropping in my own note to re-attest that the performance hit is large with optional columns. For my Excel file which had around 44,000 rows, by removing the "MakeOptional()" and assigning a default value after the process, the time went from 5-10 minutes down to under 10 seconds. I could get away with it because I was just using that mapping to assign a default value. If you actually need the functionality I am not yet sure of the work around. 

I did look at the code where the try /catch block is used and I am not yet sure how it could be restructured. If I can figure something out, I will indeed put in a pull request.

**Comment by hughbe** [comment]
What do you think about making the result nullable. i.e.
```cs
ReadCellValueResult? GetValue(ExcelSheet sheet, int rowIndex, IExcelDataReader reader)
```

Or we could have
```
bool TryGetValue(ExcelSheet sheet, int rowIndex, IExcelDataReader read)
```

**Comment by hughbe** [comment]
See #44
