### ISSUE TITLE
how to ignore the property if there is no specified column in the file?! I get an exception no read row 0

### ISSUE THREAD

**Issue by Parsifal9209** [hughbe/excel-mapper#83]
![image](https://user-images.githubusercontent.com/80875843/206676928-df388dab-c189-4d0c-99a1-2253e7506a0d.png)
![image](https://user-images.githubusercontent.com/80875843/206677221-b7b47cfe-2dac-45a3-a922-a2741faaa4ce.png)

` Map(bonus => bonus.PartnerFio)
                .WithColumnNameMatching(x => x == "partner_fio"  || x == "fio"  || x == "ФИО" || x == "ФИО Клиента")
                .WithEmptyFallback(null)
                .WithInvalidFallback(null);`

How set default value, if field not mapped

**Comment by Parsifal9209** [comment]
I'm sorry to bother you, I seem to have found what I need it is property .MapOptional().
Issue can close

**Comment by anjared** [comment]
I'm adding to this so if others stumble upon this they know the actual property is: `MakeOptional()`.  I found this to work to ignore a property that didn't exist in the file versus using the `[ExcelIgnore]` attribute on the property.

**Comment by arisliang** [comment]
I encounter the same issue, is there documentation of how to use this? Can't find `MapOptional` attribute.

**Comment by arisliang** [comment]
I find using `MakeOptional` is not ideal, because it will use custom mapping, and make `ExcelColumnName` attribute useless, please correct me if I'm wrong.

Ideally, we can still rely on `ExcelColumnName` as a default behavior, and use `ExcelIgnore`, so the column can read value if there is such column; and set to null if there is no such column.

Assuming two excel files, one with such column, and one without. And the code needs to work with both.

**Comment by hughbe** [comment]
v3 is out https://www.nuget.org/packages/ExcelDataReader.Mapping/
